// NEXUS Sandbox - Language Registry
const LANGS = {
  // WEB / FRONTEND
  'html-js':      { name:'HTML/JS/CSS',   ext:'html',  runner:'web',          cdn:[],  simOut:'', template:'<h1 style="color:#6366f1;font-family:sans-serif">Hello NEXUS!</h1>\n<button onclick="alert(\'Funciona!\')">Testar</button>\n<script>console.log("JS rodando!");<\/script>' },
  'react':        { name:'React 18',       ext:'jsx',   runner:'babel-react',  cdn:['https://unpkg.com/react@18/umd/react.development.js','https://unpkg.com/react-dom@18/umd/react-dom.development.js','https://unpkg.com/@babel/standalone/babel.min.js'], simOut:'', template:'const App=()=>{const[n,s]=React.useState(0);return<div style={{textAlign:"center",padding:40,fontFamily:"sans-serif"}}><h1 style={{color:"#6366f1"}}>React 18</h1><p>Cliques:{n}</p><button onClick={()=>s(n+1)}>+1</button></div>;};ReactDOM.createRoot(document.getElementById("root")).render(<App/>);' },
  'vue':          { name:'Vue 3',          ext:'html',  runner:'vue',          cdn:['https://unpkg.com/vue@3/dist/vue.global.js'], simOut:'', template:'<div id="app"><h1>{{msg}}</h1><button @click="c++">Cliques:{{c}}</button></div>\n<script>Vue.createApp({data(){return{msg:"Vue 3 Sandbox!",c:0}}}).mount("#app");<\/script>' },
  'tailwind':     { name:'Tailwind CSS',   ext:'html',  runner:'tailwind',     cdn:['https://cdn.tailwindcss.com'], simOut:'', template:'<div class="min-h-screen bg-gray-900 flex items-center justify-center">\n  <div class="text-center"><h1 class="text-5xl font-bold text-indigo-400 mb-4">Tailwind!</h1>\n  <button class="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-2 rounded-lg">Botão</button></div>\n</div>' },
  'typescript':   { name:'TypeScript',     ext:'ts',    runner:'babel-ts',     cdn:['https://unpkg.com/@babel/standalone/babel.min.js'], simOut:'', template:'interface User{name:string;age:number;skills:string[]}\nconst u:User={name:"NEXUS",age:25,skills:["TS","React","Design"]}\nconsole.log(`Olá ${u.name}! Skills: ${u.skills.join(", ")}`)' },
  'coffeescript': { name:'CoffeeScript',   ext:'coffee',runner:'coffeescript', cdn:['https://coffeescript.org/browser-compiler-modern/coffeescript.js'], simOut:'', template:'square = (x) -> x * x\nfor n in [1..5]\n  console.log "#{n}² = #{square n}"' },
  'elm':          { name:'Elm',            ext:'elm',   runner:'piston', simOut:'> Hello from Elm!\n> Type system is safe.', template:'module Main exposing (main)\nimport Html exposing (h1, text)\nmain = h1 [] [ text "Hello from Elm!" ]' },
  'dart':         { name:'Dart',           ext:'dart',  runner:'piston', simOut:'Hello from Dart!\n1, 2, 3, 4, 5', template:'void main() {\n  print("Hello from Dart!");\n  for (int i = 1; i <= 5; i++) print(i);\n}' },
  // SCRIPTING
  'python':       { name:'Python 3',       ext:'py',    runner:'brython',      cdn:['https://cdnjs.cloudflare.com/ajax/libs/brython/3.12.0/brython.min.js','https://cdnjs.cloudflare.com/ajax/libs/brython/3.12.0/brython_stdlib.min.js'], simOut:'', template:'import math\nfor i in range(1,6):\n    print(f"{i}! = {math.factorial(i)}")' },
  'ruby':         { name:'Ruby',           ext:'rb',    runner:'opal',         cdn:['https://cdn.opalrb.com/opal/current/opal.min.js','https://cdn.opalrb.com/opal/current/opal-parser.min.js'], simOut:'', template:'class Animal\n  def initialize(n) = @n=n\n  def falar = puts "#{@n}: Olá!"\nend\nAnimal.new("NEXUS").falar' },
  'lua':          { name:'Lua',            ext:'lua',   runner:'fengari',      cdn:['https://cdn.jsdelivr.net/npm/fengari-web@0.1.4/dist/fengari-web.js'], simOut:'', template:'local function fib(n)\n  if n<=1 then return n end\n  return fib(n-1)+fib(n-2)\nend\nfor i=0,7 do print("fib("..i..")="..fib(i)) end' },
  'perl':         { name:'Perl',           ext:'pl',    runner:'piston', simOut:'Olá Mundo!\n1 2 3 4 5', template:'#!/usr/bin/perl\nuse strict; use warnings;\nprint "Olá Mundo!\\n";\nfor my $i (1..5) { print "$i "; }\nprint "\\n";' },
  'groovy':       { name:'Groovy',         ext:'groovy',runner:'piston', simOut:'Olá do Groovy!\n[1, 2, 3, 4, 5]', template:'println "Olá do Groovy!"\ndef lista = [1,2,3,4,5]\nprintln lista.collect { it * 2 }' },
  'tcl':          { name:'Tcl',            ext:'tcl',   runner:'piston', simOut:'Olá do Tcl!\n2 4 6 8 10', template:'puts "Olá do Tcl!"\nfor {set i 1} {$i<=5} {incr i} {\n    puts -nonewline "[expr $i*2] "\n}' },
  'awk':          { name:'Awk',            ext:'awk',   runner:'piston', simOut:'NEXUS 25\nTotal linhas: 1', template:'BEGIN{\n  print "NEXUS 25"\n  count=0\n}\n{ count++ }\nEND { print "Total linhas: " count }' },
  'bash':         { name:'Bash/Shell',     ext:'sh',    runner:'piston', simOut:'Olá NEXUS!\nDiretório: /home/nexus\nScript OK', template:'#!/bin/bash\nNOME="NEXUS"\necho "Olá $NOME!"\necho "Diretório: /home/nexus"\necho "Script OK"' },
  'powershell':   { name:'PowerShell',     ext:'ps1',   runner:'piston', simOut:'Olá do PowerShell!\nVersão: 7.3\nStatus: Executado', template:'$Nome = "NEXUS"\nWrite-Host "Olá do PowerShell!"\nWrite-Host "Versão: $($PSVersionTable.PSVersion.Major).3"\nWrite-Host "Status: Executado"' },
  // SISTEMAS
  'c':            { name:'C',              ext:'c',     runner:'piston', simOut:'Olá do C!\nFatorial de 5 = 120', template:'#include <stdio.h>\nint fat(int n){return n<=1?1:n*fat(n-1);}\nint main(){\n    printf("Olá do C!\\n");\n    printf("Fatorial de 5 = %d\\n", fat(5));\n    return 0;\n}' },
  'cpp':          { name:'C++',            ext:'cpp',   runner:'piston', simOut:'Olá do C++!\nVetor: 1 4 9 16 25', template:'#include <iostream>\n#include <vector>\nusing namespace std;\nint main(){\n    cout<<"Olá do C++!"<<endl;\n    vector<int> v={1,4,9,16,25};\n    for(auto x:v) cout<<x<<" ";\n    return 0;\n}' },
  'java':         { name:'Java',           ext:'java',  runner:'piston', simOut:'Olá do Java!\nStream: [2, 4, 6, 8, 10]', template:'import java.util.*;\nimport java.util.stream.*;\npublic class Main {\n    public static void main(String[] a){\n        System.out.println("Olá do Java!");\n        System.out.println(IntStream.rangeClosed(1,5).map(x->x*2).boxed().collect(Collectors.toList()));\n    }\n}' },
  'csharp':       { name:'C#',             ext:'cs',    runner:'piston', simOut:'Olá do C#!\nLINQ: [2, 4, 6, 8, 10]', template:'using System;\nusing System.Linq;\nclass Program{\n    static void Main(){\n        Console.WriteLine("Olá do C#!");\n        var nums=Enumerable.Range(1,5).Select(x=>x*2);\n        Console.WriteLine("["+string.Join(", ",nums)+"]");\n    }\n}' },
  'go':           { name:'Go (Golang)',     ext:'go',    runner:'piston', simOut:'Olá do Go!\nConcorrência: OK\nGoroutine finalizada!', template:'package main\nimport "fmt"\nfunc main(){\n    fmt.Println("Olá do Go!")\n    ch:=make(chan string)\n    go func(){ch<-"Goroutine finalizada!"}()\n    fmt.Println("Concorrência: OK")\n    fmt.Println(<-ch)\n}' },
  'rust':         { name:'Rust',           ext:'rs',    runner:'piston', simOut:'Olá do Rust!\nSoma: 15\nMemória: segura!', template:'fn main(){\n    println!("Olá do Rust!");\n    let v=vec![1,2,3,4,5];\n    let soma:i32=v.iter().sum();\n    println!("Soma: {}",soma);\n    println!("Memória: segura!");\n}' },
  'kotlin':       { name:'Kotlin',         ext:'kt',    runner:'piston', simOut:'Olá do Kotlin!\nFiltro par: [2, 4]\nData class OK', template:'data class User(val nome:String,val age:Int)\nfun main(){\n    println("Olá do Kotlin!")\n    val nums=listOf(1,2,3,4,5)\n    println("Filtro par: ${nums.filter{it%2==0}}")\n    val u=User("NEXUS",25)\n    println("Data class OK: $u")\n}' },
  'swift':        { name:'Swift',          ext:'swift', runner:'piston', simOut:'Olá do Swift!\nOptional: NEXUS\nArray: [2, 4, 6, 8, 10]', template:'var nome:String?="NEXUS"\nprint("Olá do Swift!")\nif let n=nome{print("Optional: \\(n)")}\nlet arr=(1...5).map{$0*2}\nprint("Array: \\(arr)")' },
  'php':          { name:'PHP',            ext:'php',   runner:'piston', simOut:'Olá do PHP!\nArray: [2, 4, 6, 8, 10]\nVersione: 8.x', template:'<?php\necho "Olá do PHP!\\n";\n$nums=array_map(fn($x)=>$x*2,range(1,5));\necho "Array: [".implode(", ",$nums)."]\\n";\necho "Versão: 8.x\\n";\n?>' },
  'scala':        { name:'Scala',          ext:'scala', runner:'piston', simOut:'Olá do Scala!\nFiltro: List(2, 4)\nMap: List(1, 4, 9, 25)', template:'object Main extends App{\n  println("Olá do Scala!")\n  val nums=List(1,2,3,4,5)\n  println(s"Filtro: ${nums.filter(_%2==0)}")\n  println(s"Map: ${nums.filter(_!=3).map(x=>x*x)}")\n}' },
  // SISTEMAS / BAIXO NÍVEL
  'assembly':     { name:'Assembly x86',   ext:'asm',   runner:'piston', simOut:'; Programa executado!\n; Saída: "Hello World"\n; Retorno: 0 (sucesso)', template:'section .data\n  msg db "Hello World",10\n  len equ $ - msg\nsection .text\n  global _start\n_start:\n  mov eax,4\n  mov ebx,1\n  mov ecx,msg\n  mov edx,len\n  int 0x80' },
  'zig':          { name:'Zig',            ext:'zig',   runner:'piston', simOut:'Olá do Zig!\nSegurança: OK\nCompilação: zero-overhead', template:'const std=@import("std");\npub fn main() !void{\n    const stdout=std.io.getStdOut().writer();\n    try stdout.print("Olá do Zig!\\n",{});\n    try stdout.print("Segurança: OK\\n",{});\n}' },
  'nim':          { name:'Nim',            ext:'nim',   runner:'piston', simOut:'Olá do Nim!\n[2, 4, 6, 8, 10]', template:'echo "Olá do Nim!"\nvar nums = @[1,2,3,4,5]\necho nums.map(proc(x:int):int = x*2)' },
  'd':            { name:'D Language',     ext:'d',     runner:'piston', simOut:'Olá do D!\nRanges: [2, 4, 6, 8, 10]', template:'import std.stdio, std.algorithm, std.range;\nvoid main(){\n    writeln("Olá do D!");\n    writeln(iota(1,6).map!(a=>a*2).array);\n}' },
  'carbon':       { name:'Carbon',         ext:'carbon',runner:'piston', simOut:'Olá do Carbon!\n// Linguagem experimental do Google', template:'package MyApp api;\nfn Main() -> i32 {\n  Print("Olá do Carbon!");\n  return 0;\n}' },
  'ada':          { name:'Ada',            ext:'adb',   runner:'piston', simOut:'Olá do Ada!\nFatorial(6) = 720', template:'with Ada.Text_IO; use Ada.Text_IO;\nprocedure Main is\n  function Fat(N:Integer) return Integer is\n  begin if N<=1 then return 1; else return N*Fat(N-1); end if; end;\nbegin\n  Put_Line("Olá do Ada!");\n  Put_Line(Integer\'Image(Fat(6)));\nend Main;' },
  'pascal':       { name:'Pascal',         ext:'pas',   runner:'piston', simOut:'Olá do Pascal!\nFatorial de 5 = 120', template:'program Main;\nfunction Fat(n:Integer):Integer;\nbegin if n<=1 then Fat:=1 else Fat:=n*Fat(n-1) end;\nbegin\n  Writeln(\'Olá do Pascal!\');\n  Writeln(\'Fatorial de 5 = \',Fat(5));\nend.' },
  'fortran':      { name:'Fortran',        ext:'f90',   runner:'piston', simOut:'Olá do Fortran!\nSoma = 55', template:'program main\n  implicit none\n  integer :: i, soma\n  print *, "Olá do Fortran!"\n  soma = 0\n  do i=1,10\n    soma = soma + i\n  end do\n  print *, "Soma =", soma\nend program' },
  'cobol':        { name:'COBOL',          ext:'cbl',   runner:'piston', simOut:'OLA DO COBOL!\nSALDO: 1500.00', template:'IDENTIFICATION DIVISION.\nPROGRAM-ID. HELLO.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 SALDO PIC 9(5)V99 VALUE 1500.00.\nPROCEDURE DIVISION.\n    DISPLAY "OLA DO COBOL!"\n    DISPLAY "SALDO: " SALDO\n    STOP RUN.' },
  // DADOS / IA
  'r':            { name:'R',              ext:'r',     runner:'piston', simOut:'[1] "Olá do R!"\n[1] 1 2 3 4 5\n[1] Média: 3', template:'cat("Olá do R!\\n")\nv <- c(1,2,3,4,5)\nprint(v)\ncat("Média:",mean(v),"\\n")' },
  'julia':        { name:'Julia',          ext:'jl',    runner:'piston', simOut:'Olá do Julia!\nSoma: 55\nVetor: [1, 4, 9, 16, 25]', template:'println("Olá do Julia!")\nprintln("Soma: ", sum(1:10))\nprintln("Vetor: ", [i^2 for i in 1:5])' },
  'matlab':       { name:'MATLAB',         ext:'m',     runner:'piston', simOut:'Olá do MATLAB!\nMatriz soma = 15\nVetor: 1  4  9  16  25', template:'disp("Olá do MATLAB!")\nA = [1 2 3; 4 5 6; 7 8 9];\ndisp(["Matriz soma = " num2str(sum(A(:)))])\nv = (1:5).^2;\ndisp(v)' },
  'sql':          { name:'SQL',            ext:'sql',   runner:'alasql', cdn:['https://cdn.jsdelivr.net/npm/alasql@4.2.0/dist/alasql.min.js'], simOut:'', template:"-- SQL interativo via AlaSQL\nCREATE TABLE usuarios (id INT, nome STRING, cargo STRING);\nINSERT INTO usuarios VALUES (1,'Carlos','Dev'),(2,'Ana','Designer'),(3,'Pedro','Dev');\nSELECT nome, cargo FROM usuarios WHERE cargo='Dev';" },
  'sas':          { name:'SAS',            ext:'sas',   runner:'piston', simOut:'OBS  NOME   CARGO\n  1  Carlos  Dev\n  2  Ana     Designer', template:'data trabalho;\n  input nome $ cargo $;\n  datalines;\nCarlos Dev\nAna Designer\n;\nproc print data=trabalho; run;' },
  // FUNCIONAIS / LÓGICAS
  'haskell':      { name:'Haskell',        ext:'hs',    runner:'piston', simOut:'Olá do Haskell!\n[1,4,9,16,25]\n"NEXUS"', template:'main :: IO ()\nmain = do\n  putStrLn "Olá do Haskell!"\n  print (map (^2) [1..5])\n  print (reverse "SUXEN")' },
  'erlang':       { name:'Erlang',         ext:'erl',   runner:'piston', simOut:'Olá do Erlang!\nProcessos: assíncronos\nOK', template:'-module(hello).\n-export([main/0]).\nmain() ->\n    io:format("Olá do Erlang!~n"),\n    io:format("Processos: assíncronos~n"),\n    io:format("OK~n").' },
  'elixir':       { name:'Elixir',         ext:'ex',    runner:'piston', simOut:'Olá do Elixir!\n[2, 4, 6, 8, 10]\nProcesso: OK', template:'IO.puts "Olá do Elixir!"\nresult = Enum.map(1..5, &(&1*2))\nIO.inspect result\nIO.puts "Processo: OK"' },
  'clojure':      { name:'Clojure',        ext:'clj',   runner:'piston', simOut:'Olá do Clojure!\n(2 4 6 8 10)\n15', template:'(println "Olá do Clojure!")\n(def nums (range 1 6))\n(println (map #(* % 2) nums))\n(println (reduce + nums))' },
  'fsharp':       { name:'F#',             ext:'fs',    runner:'piston', simOut:'Olá do F#!\n[2; 4; 6; 8; 10]\nPipelined: 55', template:'printfn "Olá do F#!"\n[1..5] |> List.map ((*) 2) |> printfn "%A"\n[1..10] |> List.sum |> printfn "Pipelined: %d"' },
  'lisp':         { name:'Common Lisp',    ext:'lisp',  runner:'piston', simOut:'OLÁ DO LISP!\n(1 4 9 16 25)\n15', template:'(defun quadrado (x) (* x x))\n(print "OLÁ DO LISP!")\n(print (mapcar #\'quadrado \'(1 2 3 4 5)))\n(print (reduce #\'+ \'(1 2 3 4 5)))' },
  'scheme':       { name:'Scheme',         ext:'scm',   runner:'scheme-compiler', cdn:['https://cdn.jsdelivr.net/npm/biwascheme@0.7.5/release/biwascheme-min.js'], simOut:'', template:'(define (fat n) (if (<= n 1) 1 (* n (fat (- n 1)))))\n(display "Olá do Scheme via Compilador Nativo!") (newline)\n(display "Fatorial de 5 = ") (display (fat 5)) (newline)' },
  'prolog':       { name:'Prolog',         ext:'pl',    runner:'piston', simOut:'?- familiar(carlos, ana).\ntrue.\n?- Resp = 120\nOlá do Prolog!', template:'familiar(carlos, ana).\nfamiliar(ana, pedro).\nfatorial(0, 1) :- !.\nfatorial(N, F) :- N>0, N1 is N-1, fatorial(N1, F1), F is N*F1.\n:- write("Olá do Prolog!"), nl, fatorial(5,F), write(F).' },
  'ocaml':        { name:'OCaml',          ext:'ml',    runner:'piston', simOut:'Olá do OCaml!\n15\n[1; 4; 9; 16; 25]', template:'let () =\n  print_endline "Olá do OCaml!";\n  let soma = List.fold_left (+) 0 [1;2;3;4;5] in\n  Printf.printf "%d\\n" soma;\n  let sq = List.map (fun x -> x*x) [1;2;3;4;5] in\n  List.iter (Printf.printf "%d ") sq' },
  'sml':          { name:'Standard ML',    ext:'sml',   runner:'piston', simOut:'Olá do SML!\n120\n[2, 4, 6, 8, 10]', template:'fun fat 0 = 1 | fat n = n * fat(n-1);\nprint "Olá do SML!\\n";\nprint (Int.toString (fat 5) ^ "\\n");\nval dobros = List.map (fn x => x*2) [1,2,3,4,5];' },
  // MOBILE
  'objc':         { name:'Objective-C',    ext:'m',     runner:'piston', simOut:'Olá do Objective-C!\nArray: (1,2,3,4,5)\nNSString OK', template:'#import <Foundation/Foundation.h>\nint main(){\n  @autoreleasepool{\n    NSLog(@"Olá do Objective-C!");\n    NSArray *a=@[@1,@2,@3,@4,@5];\n    NSLog(@"Array: %@",a);\n  }\n  return 0;\n}' },
  // OUTRAS / LEGADO
  'vbnet':        { name:'VB.NET',         ext:'vb',    runner:'piston', simOut:'Olá do VB.NET!\nLista: 2 4 6 8 10\nOK', template:'Module Program\n  Sub Main()\n    Console.WriteLine("Olá do VB.NET!")\n    Dim nums As List(Of Integer)={1,2,3,4,5}\n    nums.ForEach(Sub(x) Console.Write(x*2&" "))\n  End Sub\nEnd Module' },
  'delphi':       { name:'Delphi/Pascal',  ext:'pas',   runner:'delphi-compiler', simOut:'', template:'program Delphi;\nvar i:integer;\nbegin\n  Writeln(\'Olá do Delphi! Compilado via Transpiler Customizado.\');\n  for i:=1 to 5 do Writeln(i);\nend.' },
  'abap':         { name:'ABAP (SAP)',     ext:'abap',  runner:'abap-compiler', simOut:'', template:"REPORT HELLO.\nDATA: NOME TYPE string.\nNOME = 'NEXUS'.\nWRITE: 'OLÁ DO ABAP! Rodando via Transpiler JS'.\nNEW-LINE.\nWRITE: 'USUARIO: ', NOME." },
  'apex':         { name:'Apex (Salesforce)',ext:'apex', runner:'apex-compiler', simOut:'', template:"public class Main{\n  public static void main(){\n    System.debug('Olá do Apex! Compilado diretamente no navegador.');\n    String user = 'NEXUS';\n    System.debug('Usuário Ativo: ' + user);\n  }\n}" },
  'vhdl':         { name:'VHDL',           ext:'vhd',   runner:'piston', simOut:'-- Simulação VHDL\n-- Sinal A=1, B=0\n-- Saída AND: 0\n-- Saída OR: 1', template:'library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\nentity Gate is\n  Port(A,B:in STD_LOGIC; Y_AND,Y_OR:out STD_LOGIC);\nend Gate;\narchitecture Behavioral of Gate is\nbegin\n  Y_AND<=A AND B;\n  Y_OR<=A OR B;\nend Behavioral;' },
  'verilog':      { name:'Verilog (HDL)',  ext:'v',     runner:'piston', simOut:'-- Simulação Verilog\n-- t=0: a=0,b=0, sum=0\n-- t=1: a=1,b=0, sum=1\n-- t=2: a=1,b=1, sum=0 carry=1', template:'module Somador(input a,b,output sum,carry);\n  assign sum=a^b;\n  assign carry=a&b;\nendmodule\nmodule tb;\n  reg a,b; wire s,c;\n  Somador u1(a,b,s,c);\n  initial begin\n    a=0;b=0; #1; a=1;b=0; #1; a=1;b=1;\n  end\nendmodule' },
};

// Runner CDN map (for sim languages with no CDN)
const RUNNER_CDN = {
  'alasql':    ['https://cdn.jsdelivr.net/npm/alasql@4.2.0/dist/alasql.min.js'],
  'brython':   ['https://cdnjs.cloudflare.com/ajax/libs/brython/3.12.0/brython.min.js','https://cdnjs.cloudflare.com/ajax/libs/brython/3.12.0/brython_stdlib.min.js'],
  'opal':      ['https://cdn.opalrb.com/opal/current/opal.min.js','https://cdn.opalrb.com/opal/current/opal-parser.min.js'],
  'fengari':   ['https://cdn.jsdelivr.net/npm/fengari-web@0.1.4/dist/fengari-web.js'],
  'coffeescript':['https://coffeescript.org/browser-compiler-modern/coffeescript.js'],
  'babel-react':['https://unpkg.com/react@18/umd/react.development.js','https://unpkg.com/react-dom@18/umd/react-dom.development.js','https://unpkg.com/@babel/standalone/babel.min.js'],
  'babel-ts':  ['https://unpkg.com/@babel/standalone/babel.min.js'],
  'tailwind':  ['https://cdn.tailwindcss.com'],
  'vue':       ['https://unpkg.com/vue@3/dist/vue.global.js'],
  'scheme-compiler': ['https://cdn.jsdelivr.net/npm/biwascheme@0.7.5/release/biwascheme-min.js']
};
